# Notebook nr 1: Podstawy modelowania w TensorFlow
***
Notebook zawiera ćwiczenia pozwalające na zapozananie się ze środowiskiem 
TensorFlow i schematem postępowania przy tworzeniu modeli uczenia maszynowego.

In [ ]:
import tensorflow as tf
import numpy as np

## 1. Grafy i ich wykonywanie

##### Przykład 1.1
Stworzenie grafu, a następnie jego wykonanie w sesji


In [ ]:
tf.reset_default_graph()
hello = tf.constant("Hello, world!")

with tf.Session() as sess:    
    print(sess.run(hello))

###### Ćwiczenie 1.1

Utwórz sesje, wykonaj w niej operację c.


In [ ]:
tf.reset_default_graph()
a = tf.constant(1)
b = tf.constant(2)
c = tf.add(a,b)

### MIEJSCE NA TWÓJ KOD:

    
####

Poprawny rezultat:
```
3
```

## 2. Tensory i Operacje  

### 2.1 tf.constant()

###### Przykład 2.1
tworzenie stałych w TensorFlow:

```python
x = tf.constant(3.14, dtype=tf.float32, name="x")
y = tf.constant(9, dtype=tf.int32, name="y")
```
stałe mogą być również wielowymiarowe:

```python
matrix = tf.constant([[1,3],[2,4]], name="matrix")
```
Aby uwtorzyć stałe składające sie z samych zer należy użyć  
funkcji tf.zero()
```python
zero_matrix = tf.zeros((2,3), dtype=tf.float32, name="zero_matrix")
```
otrzymamy wtedy:
```
[[0. 0. 0.]
 [0. 0. 0.]]
```
Analogiczne można utworzyć tensor składający się z samych jednynek
```python
ones_matrix = tf.ones((1,4), dtype=tf.float32, name="ones_matrix")
```
otrzymamy wtedy:
```
[[1. 1. 1. 1.]]
```

##### Ćwiczenie 2.1:
* Utwórz stałą a: macierz o wymiarach 3x3 przyjmującą kolejno wartośći od 1 do 9, typ danych tf.int32, nazwa: "a"  
* Uwtórz stałą b: macierz jedynek o wymiarach 3x3, typ danych tf.int32, nazwa "b"
* Utwórz stałą c: jako wynik dodawania stałych a i b, analogicznie jak w poprzednim przykładzie
* Uwtórz sesje i wyświel wartość stałej c

In [ ]:
tf.reset_default_graph()
# ZADANIE: Utwórz stałe a,b,c
#### Miejsce na Twój kod:
a = # 
b = #
c = # 
####

#ZADANIE: Stwórz sesje i wyświetl wartość stałej c
#### Miejsce na Twój kod:

####



Poprawny wynik:
```
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
 ```

### 2.2 Operacje matematyczne

##### Przykład 2.2

Operacje elementarne:

```python
x = tf.constant([[1,2],[3,4]], dtype=tf.float32)
y = tf.constant([[5,6],[7,8]], dtype=tf.float32)

#operacje elementarne
#dodawanie
z_add = tf.add(x, y)
# lub
z_add = x + y

#odejmowanie
z_sub = tf.subtract(x,y)
# lub
z_sub = x - y

#mnożenie
z_mult = tf.multiply(x, y)
# lub
z_mult = x * y

#dzielenie
z_div = tf.div(x,y) # podstawowy z wielu sposobów dzielenia tensorów
# lub
z_div = x / y

#Operacje na macierzach
#mnożenie macierzy
z_dot = tf.matmul(x,y)

#macierz odwrotna
x_inv = tf.matrix_inverse(x)

#macierz transponowana
x_tr = tf.transpose(x)

```

###### Ćwiczenie 2.2
Utwórz stałe z macierzy a i b, w sesji dokonaj transpozycji macierzy x, a następnie wykonaj mnożenie macierzy x i y, wyświetl wynik

In [ ]:
tf.reset_default_graph()
a = [[1,2],[5,3]]
b = [[1],[2]]

###ZADANIE
x = #Miejsce na Twój kod
y = #MIejsce na Twój kod

with tf.Session() as sess:
    ###Miejsce na Twój kod

Prawidłowy wynik:
````
[[11]
 [ 8]]
 ```

### 2.3 tf.Variable()

##### Przykład 2.3
tworzenie zmiennej:  
    Sposób I: 
  ```python    
    x = tf.Variable(3, dtype=tf.int32, name="x") 
  ```
  Sposób II:
    
  ```python
    x = tf.get_variable(name='x', initializer=tf.constant(4))
  ```
  
Inicjalizacja:  
      wszystkich zmiennych
  ```python
    sess.run(tf.global_variables_initializer())
   
  ```  
   pojedyńczej zmiennej:
   ```python
    x.initializer
    ```
   obliczenie wartości:
   ```python
    x.eval()
    ```
   Przypisanie nowej wartości:    
   ```python
     x = tf.assign(x,13) 
    ```
   efekt: x = 13  

##### Ćwiczenie 2.3
Stwórz zmienne:
* x (I Sposób, wartość 3 typ tf.int32)
* y (II sposób, nazwa 'y' typ tf.int32, initalizer tf.constant wartoś 4)    
  
W sesji zainicjuj obie zmienne i wyświetl je kolejno na ekranie

In [ ]:
tf.reset_default_graph()
x = ###Miejsce na Twój kod 
y = ###Miejsce na Twój kod

with tf.Session() as sess:
    ###Miejsce na Twój kod
    
    ###

Prawidłowy wynik:  
```
3
4
```

### 2.4 tf.Placeholder()

###### Przykład 2.4
Dostarczanie wartości do placeholdera w trakcie wykonywania sesji
```python
a = tf.placeholder(dtype=tf.float32)
b = tf.placeholder(dtype=tf.float32)
c = tf.add(a,b) 

with tf.Session() as sess:
    print(sess.run(c, feed_dict={a:8.2, b:9.1}))
```
17.3

###### Ćwiczenie 2.4.1

In [ ]:
x = tf.get_variable

## 2. Pierwszy model - binarna regresja logistyczna  
***
Do pierwszego modelu jaki stworzymy - modelu klasyfikacji binarnej - użyjemy zbioru obrazów ręcznie pisanych cyfr o wymiarach 8x8 pikseli.
Zbiór ten jest podzbiorem zbioru dostępnego pod tym [linkiem]("http://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits  
Do binarnego modelu ze zbioru danych wydzielimy tylko dwie cyfry - 0 i 1, nauczymy model odróżniać je od siebie.

Wykonamy następujące kroki:

* Załadujemy zbior i wydzielimy podzbiory treningowego i testowy
* Stworzymy graf modelu regresji logistycznej
* Przećwiczymy model
* Przeanalizujemy rezultaty

Zbiór dostępny jest w pakiecie SciKit learn.
Po zaimportowaniu go (fragmentu z 2 cyframi), mieszamy kolejnośc obserwacji  
a następnie wydzielamy zbiór treningowy i testowy.

In [ ]:
import numpy as np
from sklearn.datasets import load_digits

X,y = load_digits(n_class=2, return_X_y=True)


# Przemieszanie zbiorów
np.random.seed(54321)
p = np.random.permutation(len(y))
X = X[p]
y = y[p].reshape(-1,1)

# Jaką część zbioru stanowić ma zbiór testowy?
test_set_percentage = 0.2

# Podział na zbiory treningowy i testowy
test_set_size = round(len(y) * 0.20)
X_train = X[:-test_set_size]
y_train = y[:-test_set_size]

X_test = X[-test_set_size:]
y_test = y[-test_set_size:]

print("X dims:", X_train.shape)
print("y dims:", y_train.shape)

### Modelowanie

##### Ćwiczenie 3.1
Uwtórz placeholdery do wprowadzenia danych treningowych do modelu  
* X_input typu tf.float32, o rozmiarze None x n_inputs, name = 'X_input'  
* y_target typu tf.float32, o rozmiarze None x 1, name = 'y_target'

In [ ]:
# resetujemy graf
tf.reset_default_graph()

# liczba zmiennych wchodzących do modelu
n_inputs = X_train.shape[1]

# ZADANIE: uwtórz placeholdery dla X_input i y_target
X_input = ### Miejsce na Twój kod 
y_target = ### Miejsce na Twój kod

##### Ćwiczenie 3.2
Zainicjalizuj losowo zmienne wektorów wag
użyj funkcji tf.get_variable
jako initalizer w przypadku wag W nazwij zmienną 'Weights' i użyj tf.random_normal o odpowiednich wymiarach
wyraz wolny nazwij Bias i jako initializera użyj tf.zeros(1,1)

In [ ]:
#ZADANIE zainicjalizuj wagi
W = tf.get_variable(name=####, dtype=tf.float32, initializer=tf.random_normal((##,##), mean=0.0, stddev=0.1, seed=54321))
b = tf.get_variable(name=####, initializer=###)
                

##### Ćwiczenie 3.4
Stwórz model wg wzoru $y = X * W + b$

In [ ]:
# ZADANIE: Utwórz model
model = ### Miejsce na Twój kod

#funkcja sigmoidalna
y_pred = tf.nn.sigmoid(model)

###### Ćwiczenie 3.4
użyj tf.nn.sigmoid_cross_entropy_with_logits(), (gdzie parametr logits to model a parametr labels to zmienna celu) by obliczyć bład dla każdego przypadku, a następnie użyj tf.reduce_mean() by obliczyć średnią błędów.

In [ ]:
#ZADANIE: funkcja straty
loss = ###Miejsce na Twój kod

In [ ]:
#optymalizacja
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(loss)

##### Ćwiczenie 3.5
W sesji uwtórz pętle for, która wykona się zadaną liczbę epok (n_epochs). Podczas każdej iteracji
powinien zostać wykonany 'optimizer'. Do grafu powinnny zostać wprowadzone (feed_dict) w odpowiedni sposób dane treningowe.

In [ ]:
#trening
init = tf.global_variables_initializer()
n_epochs = 100

with tf.Session() as sess:
    sess.run(init)
    
    ###ZADANIE: Pętla for i wykonanie optimizera podczas każdej iteracji
    ### Miejsce na Twój kod
    
    
    ####
    
    #ewaluacja
    threshold = 0.5
    predictions = tf.to_float(tf.greater(y_pred, threshold))
    accuracy = tf.reduce_mean(tf.to_float(tf.equal(y_target, predictions)))
    
    print("Training set accuracy: ", accuracy.eval({X_input: X_train, y_target: y_train}))
    print("Test set accuracy: ", accuracy.eval({X_input: X_test, y_target: y_test}))